services:
  - type: web
    name: retrogarage-app
    runtime: static
    buildCommand: npm ci && npm run build:web
    staticPublishPath: ./dist
    autoDeployTrigger: commit
    envVars:
      - key: EXPO_PUBLIC_API_URL
        value: https://retrogarage-api.onrender.com/api
      - key: EXPO_PUBLIC_SIMULATIONS_API_URL
        value: https://retrogarage-simulaciones.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
